### ISSUE TITLE
to.have.focus is not present in latest npm release (2.0.0)

### ISSUE THREAD

**Issue by ming-codes** [chaijs/chai-jquery#106]
It is in master though, and it's documented in README.

**Comment by Dhaulagiri** [comment]
That change still hasn't been released (see https://github.com/chaijs/chai-jquery/issues/76).  You can get it now by pointing to a more recent sha in your package json like `chaijs/chai-jquery#e1c6697286274bc4c6170040c0f1a7742c8b5798`,

**Comment by ming-codes** [comment]
Alright, I'll close this one as duplicate.
