### ISSUE TITLE
Potential failure message improvement

### ISSUE THREAD

**Issue by gurdiga** [chaijs/chai-jquery#60]
Hey guys!

Now `expect(jQuery("div#section")).not.to.be.visible;` fails with a message like this:

```
Uncaught AssertionError: expected { Object (0, 1, ...) } not to be visible
```

It seems to me that it would be an improvement to have the failure message mention the jQuery selector instead of `{ Object (0, 1, ...) }` when it’s available. For example:
```
Uncaught AssertionError: expected 'div#section' not to be visible
```

What do you think?

**Comment by dwickern** [comment]
I finally got fed up with these terrible error messages, so I started digging.

Chai calls `chai.util.inspect(recurseTimes)` on the object, expecting the call to potentially expand to `inspect().inspect().inspect()`, until it finally returns a string, or up to `recurseTimes`.

JQuery has its own inspect function however: `jQuery.prototype.inspect(depth)` and its first argument configures how many levels of HTML to print.

So chai ends up calling `jQuery.prototype.inspect(<maximum recursion limit>)` and we get a huge HTML string back. The HTML string is longer than the `chai.config.truncateThreshold` so chai prints the object like `{ Object (0, 1, ...) }`.

##### Solution 1: disable the truncate threshold
```
chai.config.truncateThreshold = 0;
```
However now you will have paragraphs of HTML in your error messages.

##### Solution 2: overwrite $.inspect
```
var inspect = jQuery.prototype.inspect;
jQuery.prototype.inspect = function() {
  return inspect.call(this, 0); // always depth = 0
};
```
or
```
jQuery.prototype.inspect = function() {
  return '$("' + this.selector + '")'; // print out the selector instead of the HTML
};
```
