### ISSUE TITLE
doesn't work unless you include it after jquery

### ISSUE THREAD

**Issue by bcowgill** [chaijs/chai-jquery#69]
The readme instruction says all you have to do is include chai-jquery after chai
but you also have to include jquery before that. 

Was just a little confusing as to why it didn't work. 
I went to use chai-jq instead which just worked.

**Comment by keithamus** [comment]
Thanks for the issue @bcowgill.

If you want to change the README and make a pull request, we'll look toward merging it and you get a permanent place in our [hall of awesome people](https://github.com/chaijs/chai-jquery/graphs/contributors).

**Comment by T1st3** [comment]
Just added the changes to README.

**Comment by keithamus** [comment]
Great work @T1st3 :smile:

**Comment by T1st3** [comment]
@keithamus, thanks for (this incrediblely-fast) merging!
@bcowgill, thanks for the idea!
