### ISSUE TITLE
assertion for :focus

### ISSUE THREAD

**Issue by T1st3** [chaijs/chai-jquery#72]
Would you find it useful to have a new assertion for focus (as per [jQuery's focus selector](https://api.jquery.com/focus-selector/))

In the end, we would get something like: `expect('#mystuff').to.have.focus` as a new assertion.

If it makes sense to you (notably @keithamus), I'd be happy to try a PR for that!

**Comment by keithamus** [comment]
I'd say that makes perfect sense!

It should be really easy to add, all you need to do is add [`'focus'` to the list of `is` assertions, on L157-164](https://github.com/chaijs/chai-jquery/blob/master/chai-jquery.js#L157-L164). 

Of course, the trickier part might be writing tests for it. You could use one of the existing tests, for example [here is the test for `.visible`](https://github.com/chaijs/chai-jquery/blob/master/test/chai-jquery-spec.js#L437-L468).

Lastly, you'd also need to add some documentation into the README. [Maybe somewhere about here would do](https://github.com/chaijs/chai-jquery/blob/master/README.md#selected).

Let me know when you've made a PR, and I'll happily review it - with a view to merging and releasing as a minor version :smile:

**Comment by T1st3** [comment]
Thanks for this @keithamus, you definitely made the PR easier to write! I'm on it, I'll come back to you within a few hours...

**Comment by keithamus** [comment]
Feel free to take about 8 or 9 hours, as I wont be back on until then :wink:

**Comment by T1st3** [comment]
So I tried to create this new assertion...
I finally did not add 'focus' to the list of 'is' assertions as you suggested, but I created a new method for that, and I've written some tests.

The tests simply don't pass on the CLI. But after an hour of struggle, I tried to open `test/index.html` in a browser and got the tests to pass (without modifying anything).

Here is a gist of what I've actually done: https://gist.github.com/T1st3/b500986f0209466c16e5, if you'd like to check by yourself.

So, I'm still in an investigation about these tests that work in the browser but not on CLI. I think the problem is on PhantomJS's side (see a bug in PhantomJS about focus: https://github.com/ariya/phantomjs/issues/10427).

At the moment, this can't be added to the project as-is. I'm going to rethink about this before submitting a PR...

**Comment by keithamus** [comment]
@T1st3 you should absolutely file this as a PR - because we can work on it together, or others can provide input there. 

Ultimately, jQuery's `:focus` is a well tested piece of code - so if need be we can just mock jquery to ensure the assertion is calling the right things, forgoing the need for Phantom or a Phantom like environment.

I say raise the PR, and we'll

**Comment by T1st3** [comment]
Actually, I just noticed the same work has been done before in #55. @golmansax managed to pass the tests, but he used a workaround rather than jQuery's own `is(:focus)`

**Comment by T1st3** [comment]
So the tests don't pass on the CLI with PhantomJS, and they also don't pass in Google Chrome or Rekonq (all 3 are Webkit implementations).
These tests only pass when using Firefox.

**Comment by T1st3** [comment]
If I try the following workaround just before the tests for the assertion, I get the tests pass on the CLI, in Chrome and in Rekonq:

```js
  var _jQuery_is = $.fn.is;
  $.fn.is = function(s) {
  if (s === ':focus') {
    return this.get(0) === document.activeElement;
  }
    return _jQuery_is.apply(this, arguments);
  };
```

Yet, it solves the problem, but it is kind of ugly... I don't think that such monkey-patching should be used in tests.

**Comment by keithamus** [comment]
You could apply that behaviour inside of the assertions instead. Or as I say just spy on the `is` method to make sure we're calling jQuery's api and be done with it.

**Comment by T1st3** [comment]
I finally put the workaround directly in the assertion, as in commit https://github.com/chaijs/chai-jquery/commit/11ddaf979ecb5f5308fbd1610800a152a80570d5 .
Now tests pass (see PR #73).

Sorry for the delay on this!
